# Generated by Django 4.2.7 on 2023-11-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(default=93220506, max_length=10),
            preserve_default=False,
        ),
    ]
